---
title: "Práctica 2"
author: "Lorena Romero y María Soto"
date: "2023-11-22"
output:
  
  html_document:
    df_print: paged
    highlight: kate
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sys.setenv(RSTUDIO_PANDOC = "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools")

rmarkdown::render("Practica2.Rmd")



# Apartado A
## Descripción del conjunto de datos
**Describe brevemente el conjunto de entrenamiento.**

El conjunto de datos de entrenamiento consta de las siguientes variables categóricas:
`artists`, `name`, `album_name`, `album_release`, `date`, `country`, `snapshot_date`, `key`, `mode`, `time_signature`.

Y, por otra parte, las siguientes variables numéricas:
`danceability`, `energy`, `loudness`, `speechiness`, `acousticness`, `instrumentalness`, `liveness`, `valence`, `tempo`, `duration_ms`, `popularity`, `daily_rank`, `daily_movement`, `weekly_movement`.

La variable a predecir es `populariry`, que representa la popularidad de la canción con un valor numérico entre 0 y 50. Planteamos utilizar un modelo de regresión para predecir esta variable.

**Describe además, los atributos predictores del conjunto y la variable a predecir. Divide la descripción de los atributos en cuatro grupos, a saber. Justifica el porqué entiendes que cada atributo tiene o no relación con `popularity`.**

**1. predictores numéricos que, a priori, no tienen relación alguna con `popularity` y por tanto no son útiles para su predicción.**

Vamos a nombrar cada variable que pensamos que no tienen relación con su correspondiente justificación.

- `country`: la ubicación geográfica del origen de la canción no tiene una correlación evidente con su popularidad ya que la mayoría de canciones que escuchamos que son populares no sabemos cuál es su origen o no nos interesa para porder disfrutarla.

- `duration_ms`: creemos que para que una canción se haga popular no tiene que ver cómo de larga o corta es, al final si te gusta la canción no te fijas en lo que dura.

- `liveness`: si una canción se grabó en vivo o en estudio no necesariamente influye en su popularidad, es un distinto pero no implica que de una forma vaya a ser más popular que si se hubiese grabado de la otra forma.

- `time_signature`: pensamos que la escala en la que está compuesta no afectará porque da igual si está en clave de sol, de fa o de do, porque la mayoría de personas no son músicos y en lo que se fija la gente es en si suena bien la canción simplemente.

- `acousticness`: la calidad acústica de la música es algo que ha perdido importancia, pues hay canciones que no tienen calidad y aún así son muy populares, así que creemos que esto no tiene relación.

-`album_name`: muchas de las canciones no más populares no salen ni en un álbum y en general, la gente no se fija en el álbum en sí al que pertenece una canción, simplemente en la canción si les gusta. 

**2. Predictores numéricos que pueden aportar algo a la predicción de `popularity` y predictores categóricos.**

Como hemos hecho en el apartado anterior, vamos ir explicanco junto a la variable que creemos que sí puede aportar el porqué de esta creencia.

Para los predictores numéricos:

-`daily_rank`: La posición diaria en el ranking puede ser un indicador importante de la popularidad de una canción. Si una canción ocupa constantemente un lugar alto es probable que sea popular.

-`daily_movement`: El cambio diario de la posición podría indicar tendencias en la popularidad de la canción, en caso de subir seguramente indique un aumento de popularidad.

-`weekly_movement`: Es parecido al anterior, pero a más largo plazo.

-`valence`: La media de positivismo transmitido por la canción podría influir en su atractivo general, las cancioens más alegres o las más triste suelen ser las más populares pero si no trasmites nada seguramente no sea popular.

-`tempo`: El número de beats por minuto puede influir en la percepción de energía de una canción y ser más popular.

-`energy`: La energía de la canción podría ser un factor calve en su atractivo puesto que las canciones más enérgicas podrían tener mayor probabilidad de ser populares.

-`speechiness`: La presencia de palabra hablada en una canción es muy importante pues la gran mayoría de canciones (por no decir todas) que están en los rankings de popularidad suelen ser todas con letra.

-`instrumentalness`: La predominandia de la instrumentación sobre la voz pordría influir de la misma forma que la anterior.

Y para los predictores categóricos:

-`artist_name`: El artista podría ser un factor importante pues artitas más reconocidos tienen más propabilidad de producir canciones populares.

-`mode`: Si la canción está en modo mayor o menos podría influir en la percepción emocional y, por tanto, en su popularidad.

-`is_explicit`: La presencia de lenguaje explícito podría atraet a ciertos públicos y afectar. Por ejemplo, muchas canciones muy populares latinoamericanas tienen un alto porcentaje de palabras sexuales y escenarios explícitos y, a veces, cuan más explícito es más repercusión tiene. Por otra parte, canciones con un lenguaje explícito de violencia no suelen ser populares por motivos obvios.

-`danceability`: La capacidad de una canción para ser baildad podría ser una factor importante.

**3. Relacionados con `popularity`.**

Pensamos que las variables que más relación tienen con la popularidad son los puestos que tiene una canción diariamente y semanal y sus movimientos entre los puestos. `daily_rank`, `daily_movement` y `weekly_movement`.


**4. No relacionados.**

spotify_id, name, country, duration_ms??, album_name, liveness, key, loudness

# Apartado B
## Preparación de datos
**Respóndase a las siguientes preguntas en relación a la preparación de datos.**

**- ¿Qué predictores habría que normalizar? ¿Por qué? ¿Cuál sería la estrategia de normalización en cada caso?**

**- ¿Podría ser interesante transformar algún atributo o grupos de atributos en uno nuevo? ¿Por qué?**

**- ¿Cómo podría aprovecharse el carácter secuencial de los datos?**


# Apartado C
## Fucnionamiento
**Explicar brevemente el tipo de modelo que genera el algoritmo, y cuál es la estrategia de dicho algoritmos para construir el modelo.**

## Requisitos
**Indicar si el algoritmo en cuestión tiene algún requisito en cuanto a si se han de preprocesar los datos (e.g. escalado, imputación de valores nulos, etc.) y cómo. Explicar cómo se ha tenido en cuenta estos requisitos a la hora de generar los datos de training específicos para este algoritmo.**

## Descripción de hiperparámetros
**Identificar y explicar cada uno de sus parámetros de configuración.**

## Grid Hiperparámetros
**Detallar una estrategia para la generación del grid de valores para hiperparámetros a usar.**

## Resultados
**Describir los resultados del algoritmo.**

# Apartado D
## Modelo Final